---
version: "3.8"

services:
  zammad-nginx:
    environment:
      - VIRTUAL_HOST=	zammad.dev.network.as212655.net
      - NGINX_SERVER_SCHEME=https
    networks:
      - default
      - youfibre_external
    deploy:
      labels:
        caddy: zammad.dev.network.as212655.net
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls.dns: route53
      
networks:
  youfibre_external:
    driver: overlay # Use when deploying over Docker Swarm
    external: tru
